# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Year', models.IntegerField(max_length=4)),
                ('Studio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_name', models.CharField(max_length=25)),
                ('Bday', models.DateTimeField(verbose_name='D.O.B')),
                ('Literacy_agency', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='Mwriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.Writer'),
        ),
    ]
