# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_auto_20171101_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='Bday',
            field=models.DateField(verbose_name='D.O.B'),
        ),
    ]
