# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0003_auto_20171101_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
