# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0006_auto_20171104_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='Writer',
            new_name='W_name',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='Writer_pic',
            new_name='W_pic',
        ),
    ]
