# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0007_auto_20171104_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='M_logo',
        ),
        migrations.AlterField(
            model_name='writer',
            name='W_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
