# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0009_auto_20171105_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Mwriter',
            new_name='Movie_writer',
        ),
    ]
