# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvseries', '0010_auto_20171106_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
