# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0011_writer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_favourite',
        ),
    ]
