# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0012_remove_movie_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Total_seasons', models.IntegerField()),
                ('Series_Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.Writer')),
            ],
        ),
    ]
